services:
  - type: web
    name: cricket-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
      - src/**
      - public/**
      - scripts/**
      - package.json
      - server.js